from __future__ import annotations

import argparse
import re
from pathlib import Path

from generate_card_catalog import TEXT_ACCENTS


DOCUMENT_ACCENTS = {
    "abandonnees": "abandonnées",
    "abreges": "abrégés",
    "absorbee": "absorbée",
    "activites": "activités",
    "affectees": "affectées",
    "agressivite": "agressivité",
    "ajoutees": "ajoutées",
    "ambiguites": "ambiguïtés",
    "anglo-americain": "anglo-américain",
    "anterieures": "antérieures",
    "anti-rhetorique": "anti-rhétorique",
    "archivee": "archivée",
    "bibliotheque": "bibliothèque",
    "brievement": "brièvement",
    "causalite": "causalité",
    "chargees": "chargées",
    "cinematographiques": "cinématographiques",
    "chaines": "chaînes",
    "circularites": "circularités",
    "citees": "citées",
    "classee": "classée",
    "cle": "clé",
    "cles": "clés",
    "comparee": "comparée",
    "comparees": "comparées",
    "complete": "complète",
    "completer": "compléter",
    "comptee": "comptée",
    "concentree": "concentrée",
    "concretise": "concrétise",
    "conference": "conférence",
    "confrontee": "confrontée",
    "confrontees": "confrontées",
    "conservees": "conservées",
    "conserves": "conservés",
    "consolidee": "consolidée",
    "contestee": "contestée",
    "contestees": "contestées",
    "controles": "contrôles",
    "creee": "créée",
    "creees": "créées",
    "crees": "créés",
    "curiosite": "curiosité",
    "d'autorite": "d'autorité",
    "d'autorites": "d'autorités",
    "d'entree": "d'entrée",
    "debat": "débat",
    "decisives": "décisives",
    "declenchement": "déclenchement",
    "declin": "déclin",
    "decodes": "décodés",
    "decorative": "décorative",
    "decrites": "décrites",
    "defend": "défend",
    "defendable": "défendable",
    "defendre": "défendre",
    "defendue": "défendue",
    "defendues": "défendues",
    "definissent": "définissent",
    "definition": "définition",
    "deformante": "déformante",
    "degager": "dégager",
    "delimitee": "délimitée",
    "demolition": "démolition",
    "demontrees": "démontrées",
    "dependances": "dépendances",
    "depot": "dépôt",
    "derivees": "dérivées",
    "derniere": "dernière",
    "desaccord": "désaccord",
    "desormais": "désormais",
    "detaillee": "détaillée",
    "determinees": "déterminées",
    "developpee": "développée",
    "developpees": "développées",
    "developpent": "développent",
    "developpes": "développés",
    "deviante": "déviante",
    "differentielle": "différentielle",
    "distillees": "distillées",
    "distilles": "distillés",
    "distinguees": "distinguées",
    "echanges": "échanges",
    "echantillon": "échantillon",
    "ecris": "écris",
    "ecrits": "écrits",
    "editorial": "éditorial",
    "editoriale": "éditoriale",
    "editoriales": "éditoriales",
    "elastique": "élastique",
    "emergence": "émergence",
    "emergent": "émergent",
    "emotion": "émotion",
    "entamee": "entamée",
    "entree": "entrée",
    "entrees": "entrées",
    "equivalent": "équivalent",
    "esquissees": "esquissées",
    "esthetiques": "esthétiques",
    "etablie": "établie",
    "etat": "état",
    "etude": "étude",
    "evitant": "évitant",
    "evolutives": "évolutives",
    "exigee": "exigée",
    "experimentation": "expérimentation",
    "explicitees": "explicitées",
    "expliquee": "expliquée",
    "fermete": "fermeté",
    "forme-memoire": "forme-mémoire",
    "formulees": "formulées",
    "francais": "français",
    "francaise": "française",
    "frontiere": "frontière",
    "fusionnee": "fusionnée",
    "fusionnes": "fusionnés",
    "generalisent-ils": "généralisent-ils",
    "generaux": "généraux",
    "generees": "générées",
    "geographie": "géographie",
    "geographiques": "géographiques",
    "granularite": "granularité",
    "honnetete": "honnêteté",
    "idealement": "idéalement",
    "idees": "idées",
    "identifiees": "identifiées",
    "immediat": "immédiat",
    "immediates": "immédiates",
    "independante": "indépendante",
    "indiquee": "indiquée",
    "inference": "inférence",
    "inferieur": "inférieur",
    "ingere": "ingéré",
    "ingerer": "ingérer",
    "inseparable": "inséparable",
    "inspectee": "inspectée",
    "inspirees": "inspirées",
    "instantanes": "instantanés",
    "inferentiels": "inférentiels",
    "integrale": "intégrale",
    "integralite": "intégralité",
    "integree": "intégrée",
    "integrent": "intègrent",
    "integrer": "intégrer",
    "integrite": "intégrité",
    "interdependance": "interdépendance",
    "intermediaire": "intermédiaire",
    "interpretatives": "interprétatives",
    "inventee": "inventée",
    "inventees": "inventées",
    "inventoriee": "inventoriée",
    "inventoriees": "inventoriées",
    "inventories": "inventoriés",
    "irreversible": "irréversible",
    "iterative": "itérative",
    "l'age": "l'âge",
    "l'annee": "l'année",
    "l'editeur": "l'éditeur",
    "l'impossibilite": "l'impossibilité",
    "l'inference": "l'inférence",
    "l'interdependance": "l'interdépendance",
    "laissees": "laissées",
    "legale": "légale",
    "limitees": "limitées",
    "lisibilite": "lisibilité",
    "localisees": "localisées",
    "majeste": "majesté",
    "malediction": "malédiction",
    "marquee": "marquée",
    "melange": "mélange",
    "metadonnees": "métadonnées",
    "methodes": "méthodes",
    "methodiquement": "méthodiquement",
    "methodologiques": "méthodologiques",
    "metrique": "métrique",
    "micro-emotions": "micro-émotions",
    "mobilisee": "mobilisée",
    "modelisation": "modélisation",
    "multidimensionnalite": "multidimensionnalité",
    "modifiee": "modifiée",
    "modifiees": "modifiées",
    "negatifs": "négatifs",
    "nes": "nés",
    "operatoires": "opératoires",
    "oubliees": "oubliées",
    "plaquees": "plaquées",
    "portee": "portée",
    "precedente": "précédente",
    "precedentes": "précédentes",
    "precisee": "précisée",
    "precisees": "précisées",
    "precisent": "précisent",
    "precises": "précises",
    "precisions": "précisions",
    "premiere": "première",
    "preparatoire": "préparatoire",
    "priorite": "priorité",
    "proximite": "proximité",
    "proximites": "proximités",
    "quatrieme": "quatrième",
    "raccordee": "raccordée",
    "raccordees": "raccordées",
    "raccorde": "raccordé",
    "rarefaction": "raréfaction",
    "rattachee": "rattachée",
    "rattachees": "rattachées",
    "recits": "récits",
    "recommandee": "recommandée",
    "recurrences": "récurrences",
    "rediges": "rédigés",
    "reeducation": "rééducation",
    "reels": "réels",
    "reference": "référence",
    "references": "références",
    "reflexives": "réflexives",
    "reformulees": "reformulées",
    "refugie": "réfugie",
    "refutee": "réfutée",
    "regenere": "régénéré",
    "regles": "règles",
    "regroupees": "regroupées",
    "releve": "relève",
    "reliee": "reliée",
    "reliees": "reliées",
    "renforcee": "renforcée",
    "renforcees": "renforcées",
    "reperees": "repérées",
    "reperes": "repères",
    "repertoire": "répertoire",
    "repertorie": "répertorie",
    "representees": "représentées",
    "representes": "représentés",
    "resiste": "résiste",
    "resultats": "résultats",
    "resumes": "résumés",
    "retroaction": "rétroaction",
    "reutilisable": "réutilisable",
    "reutilisables": "réutilisables",
    "reutilises": "réutilisés",
    "reversible": "réversible",
    "revisable": "révisable",
    "reviser": "réviser",
    "revision": "révision",
    "rhetoriques": "rhétoriques",
    "roles": "rôles",
    "schema": "schéma",
    "selective": "sélective",
    "sequentiel": "séquentiel",
    "serieuses": "sérieuses",
    "severite": "sévérité",
    "signalee": "signalée",
    "specialisees": "spécialisées",
    "specialises": "spécialisés",
    "specificite": "spécificité",
    "speculatives": "spéculatives",
    "stabilisee": "stabilisée",
    "stabilisees": "stabilisées",
    "structurees": "structurées",
    "subjectivite": "subjectivité",
    "suggerees": "suggérées",
    "superieure": "supérieure",
    "supposee": "supposée",
    "supprimee": "supprimée",
    "supprimes": "supprimés",
    "symptomes": "symptômes",
    "synthetique": "synthétique",
    "synthetisees": "synthétisées",
    "synthetiseur": "synthétiseur",
    "systematique": "systématique",
    "temporalite": "temporalité",
    "theatrale": "théâtrale",
    "thematique": "thématique",
    "thematiques": "thématiques",
    "theme": "thème",
    "themes": "thèmes",
    "theoriques": "théoriques",
    "these": "thèse",
    "theses": "thèses",
    "tonalite": "tonalité",
    "tracabilite": "traçabilité",
    "traitee": "traitée",
    "traitees": "traitées",
    "typee": "typée",
    "typees": "typées",
    "utilisees": "utilisées",
    "validite": "validité",
    "verifiable": "vérifiable",
    "verification": "vérification",
    "verifiee": "vérifiée",
    "verifiees": "vérifiées",
    "vertebrale": "vertébrale",
    "virtuosite": "virtuosité",
    "reactive": "réactivé",
    "autonomises": "autonomisés",
    "atomises": "atomisés",
    "bayesien": "bayésien",
    "compares": "comparés",
    "decodables": "décodables",
    "dezippe": "dézippé",
    "dezippee": "dézippée",
    "operationnalisation": "opérationnalisation",
    "epistemique": "épistémique",
    "inventorie": "inventorié",
    "publie": "publié",
    "raccordes": "raccordés",
    "regroupes": "regroupés",
    "sourcees": "sourcées",
    "supprime": "supprimé",
    "versionne": "versionné",
    "audites": "audités",
    "documentes": "documentés",
    "incorpores": "incorporés",
    "proposes": "proposés",
    "termines": "terminés",
}

TEXT_ACCENTS.update(DOCUMENT_ACCENTS)


FRENCH_DOCUMENTS = (
    "README.md",
    "bibliographie/README.md",
    "cartes/AUDIT_PROPOSITIONS.md",
    "cartes/COUVERTURE_EXTRACTION.md",
    "cartes/ORDRE_TRAITEMENT_DOCUMENTS.md",
    "cartes/ORGANISATION.md",
    "cartes/PLAN_DOCUMENTS.md",
    "cartes/README.md",
    "cartes/REGISTRE_TRAITEMENT.md",
    "cartes/indexes/by_argument.md",
    "cartes/indexes/by_level.md",
    "cartes/indexes/by_theme.md",
    "input/README.md",
    "projet-these/CHANGELOG.md",
    "projet-these/BUT_DE_LA_THESE.md",
    "projet-these/README.md",
    "prompts/constructeur.md",
    "prompts/critique.md",
    "prompts/digest.md",
    "prompts/final_synthesis.md",
    "prompts/synthetiseur.md",
)

PROTECTED_RE = re.compile(
    r"(?P<fence>^```.*?^```[ \t]*$)"
    r"|(?P<inline>`[^`\n]+`)"
    r"|(?P<link_destination>\]\([^\n)]+\))"
    r"|(?P<template_variable>\$[A-Za-z_][A-Za-z0-9_]*)"
    r"|(?P<url>https?://\S+)",
    re.MULTILINE | re.DOTALL,
)

ACCENT_RE = re.compile(
    rf"(?<!\w)({'|'.join(re.escape(word) for word in sorted(TEXT_ACCENTS, key=len, reverse=True))})(?!\w)",
    re.IGNORECASE,
)

CONTEXTUAL_REPLACEMENTS = (
    (r"\ba l'", "à l'"),
    (r"\ba la\b", "à la"),
    (r"\ba un\b", "à un"),
    (r"\ba une\b", "à une"),
    (r"\ba des\b", "à des"),
    (r"\ba ce\b", "à ce"),
    (r"\ba cet\b", "à cet"),
    (r"\ba cette\b", "à cette"),
    (r"\ba ces\b", "à ces"),
    (r"\ba son\b", "à son"),
    (r"\ba sa\b", "à sa"),
    (r"\ba ses\b", "à ses"),
    (r"\ba leur\b", "à leur"),
    (r"\ba leurs\b", "à leurs"),
    (r"\ba chaque\b", "à chaque"),
    (r"\ba plusieurs\b", "à plusieurs"),
    (r"\ba deux\b", "à deux"),
    (r"\ba trois\b", "à trois"),
    (r"\ba six\b", "à six"),
    (r"\ba sept\b", "à sept"),
    (r"\ba neuf\b", "à neuf"),
    (r"\ba onze\b", "à onze"),
    (r"\ba douze\b", "à douze"),
    (r"\ba état\b", "à état"),
    (r"\ba boucles\b", "à boucles"),
    (r"\ba somme\b", "à somme"),
    (r"\ba partir\b", "à partir"),
    (r"\ba travers\b", "à travers"),
    (r"\ba nouveau\b", "à nouveau"),
    (r"\ba mesure\b", "à mesure"),
    (r"\ba condition\b", "à condition"),
    (r"\ba force\b", "à force"),
    (r"\ba propos\b", "à propos"),
    (r"\ba jour\b", "à jour"),
    (r"\ba l'épreuve\b", "à l'épreuve"),
    (r"\ba (?=[A-Za-zÀ-ÖØ-öø-ÿŒœ-]+(?:er|ir|re)\b)", "à "),
    (r"\bne résumé pas\b", "ne résume pas"),
    (r"\bcontrôle detaille\b", "contrôle détaillé"),
    (r"\bAudit réalise\b", "Audit réalisé"),
    (r"\| traite\b", "| traité"),
    (r"\| inventorie(?=\s*(?:;|\|))", "| inventorié"),
    (r"\bsera traite\b", "sera traité"),
    (r"\bdéjà traite\b", "déjà traité"),
    (r"\bdocuments? traite\b", lambda match: match.group(0)[:-6] + "traité"),
    (r"\bconjectures non demontrees\b", "conjectures non démontrées"),
    (r"\bnon eriges\b", "non érigés"),
    (r"\bPrefixe?s elimines\b", "Préfixes éliminés"),
    (r"\bcritères administratifs ecartes\b", "critères administratifs écartés"),
    (r"\brésultats déjà representes\b", "résultats déjà représentés"),
    (r"\bont été traites\b", "ont été traités"),
    (r"\bont été distingues\b", "ont été distingués"),
    (r"\ba été supprime\b", "a été supprimé"),
    (r"\bcomme doublon supprime\b", "comme doublon supprimé"),
    (r"\bdoublon supprime\b", "doublon supprimé"),
    (r"\bdoublon vérifie et supprime\b", "doublon vérifié et supprimé"),
    (r"\bzip supprime\b", "zip supprimé"),
    (r"\bPDF canonique conserve\b", "PDF canonique conservé"),
    (r"\bait laisse\b", "ait laissé"),
    (r"\bproblème invente\b", "problème inventé"),
    (r"\bont renforce\b", "ont renforcé"),
    (r"\ba renforce\b", "a renforcé"),
    (r"\brestent archives\b", "restent archivés"),
    (r"\bnon analyse harmoniquement\b", "non analysé harmoniquement"),
    (r"\bnon analyses harmoniquement\b", "non analysés harmoniquement"),
    (r"\béchantillon de pages contrôle\b", "échantillon de pages contrôlé"),
    (r"\bDigest intégral filtre\b", "Digest intégral filtré"),
    (r"\bjeu producteur-auditeur traite\b", "jeu producteur-auditeur traité"),
    (r"\bdétails non autonomises\b", "détails non autonomisés"),
    (r"\brégime graduel distingue\b", "régime graduel distingué"),
    (r"\bfragment inventorie\b", "fragment inventorié"),
    (r"\bprogramme (?:de recherche |empirique )?inventorie\b", lambda match: match.group(0)[:-10] + "inventorié"),
    (r"\bdoivent être analyses\b", "doivent être analysés"),
    (r"\bnon analyses harmoniquement\b", "non analysés harmoniquement"),
    (r"\bdoivent être cites\b", "doivent être cités"),
    (r"\bne doivent pas être ajoutes\b", "ne doivent pas être ajoutés"),
    (r"\bconsacre a (?=\*\*)", "consacré à "),
    (r"\bà état borne\b", "à état borné"),
    (r"\bdoit être mesure\b", "doit être mesuré"),
    (r"\ba été confronte\b", "a été confronté"),
    (r"\ba été transforme\b", "a été transformé"),
    (r"\ba été contrôle\b", "a été contrôlé"),
    (r"\btable a été contrôlé\b", "table a été contrôlée"),
    (r"\bcas Butler conserve\b", "cas Butler conservé"),
    (r"\best conserve comme\b", "est conservé comme"),
    (r"\bsentiment d'avancer conserve\b", "sentiment d'avancer conservé"),
    (r"\bNoyaux examines\b", "Noyaux examinés"),
    (r"\bdocuments examines\b", "documents examinés"),
    (r"\baucun manque propositionnel identifie\b", "aucun manque propositionnel identifié"),
    (r"\bapplication non autonomisee\b", "application non autonomisée"),
    (r"\bétat borne\b", "état borné"),
    (r"\bcontrôle\s+detaille\b", "contrôle détaillé"),
    (r"\bElle isolé\b", "Elle isole"),
    (r"(`idea_0111`) isolé\b", r"\1 isole"),
    (r"\bfragments filtres\b", "fragments filtrés"),
)

FINAL_REPLACEMENTS = (
    (r"(`idea_\d{4}`) a (`idea_\d{4}`)", r"\1 à \2"),
    (r"\b(raccord(?:é|ée|és|ées)|compar(?:é|ée|és|ées)) a (?=`)", r"\1 à "),
    (r"\bDOCX a été supprimé, (`[^`]+`) conserve\b", r"DOCX a été supprimé, \1 conservé"),
    (r"\bcompare intégralement a (?=`)", "comparé intégralement à "),
    (r"\bont été raccordes a (?=`)", "ont été raccordés à "),
    (r"\ba en outre renforce (?=`)", "a en outre renforcé "),
)

LITERAL_REPLACEMENTS = {
    "controle detaille de la couverture propositionnelle": "contrôle détaillé de la couverture propositionnelle",
    "proposition restent regroupes": "proposition restent regroupés",
    "controles du moteur et des metadonnees": "contrôles du moteur et des métadonnées",
    'Question philosophique delimitee': 'Question philosophique délimitée',
    "emergence d'une forme": "émergence d'une forme",
    "relation forme-memoire": "relation forme-mémoire",
    "temporalite de l'agencement": "temporalité de l'agencement",
    "frontiere du presque-apprenable": "frontière du presque-apprenable",
    "necessite inventee": "nécessité inventée",
    "solution rare d'un probleme implicite": "solution rare d'un problème implicite",
    "micro-emotions et variations": "micro-émotions et variations",
    "distinction resultats / idees / articulations": "distinction résultats / idées / articulations",
    "`la curiosite`": "`la curiosité`",
    "### Version forte de la these": "### Version forte de la thèse",
    "### Distinctions decisives": "### Distinctions décisives",
    "### Conditions de validite et de portee": "### Conditions de validité et de portée",
    "### Paragraphe reutilisable": "### Paragraphe réutilisable",
    "Paragraphe reutilisable": "Paragraphe réutilisable",
    "## Noyau de these": "## Noyau de thèse",
    "## Distinctions operatoires": "## Distinctions opératoires",
    "## These consolidee": "## Thèse consolidée",
    "## Conditions de validite": "## Conditions de validité",
    "## Reformulation de la these pour la suite": "## Reformulation de la thèse pour la suite",
    "### Pourquoi cela resiste mal": "### Pourquoi cela résiste mal",
    "### Revision exigee": "### Révision exigée",
    "references et regles bibliographiques": "références et règles bibliographiques",
    "roles et prompts de dialogue": "rôles et prompts de dialogue",
    "anciens runs et sorties generees": "anciens runs et sorties générées",
    "etat des runs": "état des runs",
    "gain propre a un observateur": "gain propre à un observateur",
    "rangs 17 a 31": "rangs 17 à 31",
    "comparées a KDD95": "comparées à KDD95",
    "comparée a NetNeg": "comparée à NetNeg",
    "France-Bresil-monde": "France-Brésil-monde",
    " / Celine": " / Céline",
    "Effet Menard": "Effet Ménard",
    "boucle semantique": "boucle sémantique",
    "temporel/atemporal": "temporel/atemporel",
}


def restore_accents(text: str) -> str:
    def replace_word(match: re.Match[str]) -> str:
        replacement = TEXT_ACCENTS[match.group(0).lower()]
        if match.group(0)[0].isupper():
            return replacement[0].upper() + replacement[1:]
        return replacement

    text = ACCENT_RE.sub(replace_word, text)
    for pattern, replacement in CONTEXTUAL_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text


def normalize_document(text: str) -> str:
    parts: list[str] = []
    cursor = 0
    for match in PROTECTED_RE.finditer(text):
        parts.append(restore_accents(text[cursor : match.start()]))
        parts.append(match.group(0))
        cursor = match.end()
    parts.append(restore_accents(text[cursor:]))
    text = "".join(parts)
    for pattern, replacement in FINAL_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    for source, target in LITERAL_REPLACEMENTS.items():
        text = text.replace(source, target)
    return text


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Restore French diacritics in the project's prose documents"
    )
    parser.add_argument("--check", action="store_true", help="List files needing changes")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    changed: list[Path] = []
    for relative_path in FRENCH_DOCUMENTS:
        path = project_root / relative_path
        original = path.read_text(encoding="utf-8")
        updated = normalize_document(original)
        if updated == original:
            continue
        changed.append(path)
        if not args.check:
            path.write_text(updated, encoding="utf-8")

    action = "need normalization" if args.check else "normalized"
    print(f"{len(changed)} document(s) {action}.")
    for path in changed:
        print(path.relative_to(project_root))


if __name__ == "__main__":
    main()
